### ISSUE TITLE
CFU in batch mode

### ISSUE THREAD

**Issue by Sihao** [yu-lab-vt/AQuA2#4]
Is it possible to include the CFUs in the output from the batch mode script?
Alternatively, is it possible to use the GUI for the CFU operations using the output from the events saved through the batch script?

Thanks

**Comment by XuelongMi** [comment]
Hi Sihao,

"post_cfu_cmd_batch.m" is added so that it can detect CFU based on events saved through the batch script. (To use this script, some files are updated, so maybe you should download the new version from GitHub)

Besides, by typing "aqua_gui(res)" in the MATLAB Command Window after loading the saved file obtained from batch script, you can open GUI and load the events detected. Then you can do the CFU operations on that GUI by clicking "CFU detect".

Best Wishes,
Xuelong Mi

**Comment by XuelongMi** [comment]
Could I close this comment?
